### ISSUE TITLE
As an event planner specialising in large events such as weddings, I want to tag all my guests in the list at once

### ISSUE THREAD

**Issue by aaryamNUS** [CS2113-AY1819S1-F09-3/main#89]
So that I can save a lot of time and increase efficiency, as opposed to editing the tags of each individual person.

**Comment by aaryamNUS** [comment]
This user story has been met in v1.2. The various tasks needed to complete this story are as follows:
- [x] Modify the current Model API to support the use of a removeTag() command. (Issue #120)
- [x] Implement the logic and parser of the removeTag() command. (Issue #121)
- [x] Modify the current model API to allow an addTag() command. (Issue #122)
- [x] Implement the logic and parser of the addTag() command. (Issue #123)
- [x] Create tests in AddressBookTest.java to test addTag() and removeTag() API changes. (Issue #124)
- [x] Refactor code for addTag(), removeTag(), and tag colour generation. (Issue #125)
- [x] Error handling for move addTag() and removeTag()
- [x] Editions and additions to the UserGuide and DeveloperGuide. (Issue #126)
- [x] Refactored code for tag colour generation and new commands added
